name: Build the latex manuscript
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: tex
          root_file: astropy-paper-3.tex
      - name: HACK - remove gitignore so PDF is added and deployed
        run: rm tex/.gitignore
      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tex
          force_orphan: true